# Generated by Django 3.0.6 on 2020-05-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='system_iot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_system', models.IntegerField()),
                ('date', models.DateField()),
                ('rul', models.IntegerField()),
                ('values', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='user_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_model', models.IntegerField()),
                ('user_name', models.CharField(default='', max_length=50)),
                ('model_name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='user_system',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_system', models.IntegerField()),
                ('user_name', models.CharField(default='', max_length=50)),
                ('system_name', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
