# Generated by Django 3.0.6 on 2020-05-25 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pdm_site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system_iot',
            name='id_system',
        ),
        migrations.RemoveField(
            model_name='user_model',
            name='id_model',
        ),
        migrations.RemoveField(
            model_name='user_model',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='user_system',
            name='id_system',
        ),
        migrations.RemoveField(
            model_name='user_system',
            name='user_name',
        ),
        migrations.AddField(
            model_name='system_iot',
            name='system_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pdm_site.user_system'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_model',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_system',
            name='model_id',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='pdm_site.user_model'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_system',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
