# Generated by Django 3.0.6 on 2020-06-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdm_site', '0002_auto_20200525_2322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='system_iot',
            old_name='rul',
            new_name='sensor_id',
        ),
        migrations.RemoveField(
            model_name='user_system',
            name='model_id',
        ),
        migrations.AddField(
            model_name='user_system',
            name='rul',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='user_model',
        ),
    ]
